os:
  - osx

sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
before_script:
before_install:
  - wget http://www.sfml-dev.org/files/SFML-2.4.0-osx-clang.tar.gz
  - tar -zxvf SFML-2.4.0-osx-clang.tar.gz
  - cd SFML-2.4.0-osx-clang
  - sudo cp -r lib/* /usr/local/lib/
  - sudo cp -r Frameworks/ /Library/Frameworks/
  - sudo cp -r  include /usr/local/include
  - sudo cp extlibs/sndfile.framework  /Library/Frameworks
  - sudo cp extlibs/freetype.framework  /Library/Frameworks
#  - d 755 install.sh
#  - bash ./install.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 cppcheck libsfml-dev; fi
  - export PATH=$PATH:/usr/local/bin
script: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5         ; fi
 # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/bin/qmake -spec macx-xcode pagan_board.pro          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -lah /usr/local/bin/          ; fi
  - cd ..
  - pwd
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/bin/qmake -spec macx-xcode pagan_board.pro          ; fi
  - ls
#  - qmake -makefile pagan_board.pro && make && make && cppcheck . --enable=all 
  - xcodebuild -list -project pagan_board.xcodeproj
  - xcodebuild -scheme pagan_board build
  - ls
