name: deerportal
version: "0.7.5-more-plugs"
summary: Deer Portal" snap
description: Board game where you need to transfer yourself into the Deer God
grade: stable
confinement: strict
apps:
  deerportal:
    command: DeerPortal
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
parts:
  source-deerportal:
    plugin: cmake
    #source: /tmp/v0.7.3-pre-snap.tar.gz
    source: https://github.com/deerportal/deerportal.git
    source-type: git
    #source: https://github.com/deerportal/deerportal/archive/v0.7.3-pre-snap.tar.gz
    source-depth: 1
    build-packages:
      - libsfml-dev
      - libgl1-mesa-dri
      - libopenal-dev


