name: deerportal
version: "0.7.5-more-plugs"
summary: Deer Portal" snap
description: Board game where you need to transfer yourself into the Deer God
grade: stable
confinement: strict
apps:
  deerportal:
    command: DeerPortal
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
#      - alsa
parts:
#  alsa:
#    after: [alsa-lib, alsa-plugins]
#  alsa-plugins:
#    after: [alsa-lib]      
  source-deerportal:
    after: [desktop-gtk3]
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release  
      - -DCMAKE_INSTALL_PREFIX=/usr
    source: https://github.com/deerportal/deerportal.git
    source-type: git
    source-depth: 1
    build-packages:
      - libsfml-dev
      - libgl1-mesa-dri
      - libopenal-dev
      - libsndio-dev
#    stage-packages:
#      - libc6
#      - alsa



