name: deerportal
version: "0.7.2-pre-snap"
summary: Deer POrtal" snap
description: Board game where you need to transfer yourself into the Deer God
grade: stable
confinement: strict
apps:
  deerportal:
    command: DeerPortal
parts:
  source-deerportal:
    plugin: cmake
    source: https://github.com/deerportal/deerportal/archive/v0.7.2-pre-snap.tar.gz